### ISSUE TITLE
    raise KeyError(f"{not_found} not in index") 

### ISSUE THREAD

**Issue by mital14** [CarmenSheppard/PneumoKITy#38]
KeyError: "['Serotype', 'shared-hashes', 'median-multiplicity', 'p-value'] not in index"
encountering this error and dont know how to fix, please help

**Comment by CarmenSheppard** [comment]
Hi, 

I'd need quite a bit more info in order to help. Can you give me the commandline you are using, and the full output of the python error - it should indicate a line number etc.  From what you've posted it looks like it's trying to find the wrong thing and shouldn't have got where it is, but I don't know where that is or how it got there.

**Comment by mital14** [comment]
Hi, i found that i was using different pandas version which caused issue, it is solved now, Thanks a ton for the response.
